[package]
description = "Webots bindings for Rust"
edition = "2024"
homepage = "https://github.com/HULKs/webots-rs"
license = "MIT"
name = "webots"
version = "0.8.0"

[dependencies]
libc = "0.2"
thiserror = "2.0"
tracing = "0.1"
webots-bindings = { path = "webots-bindings", version = "0.8.0" }

[[example]]
name = "basics"
path = "examples/controllers/basics/basics.rs"
